export const ActionTypes = {
  ADD_TODO_TASK : 'ADD_TODO_TASK',
  REMOVE_TODO_TASK : 'REMOVE_TODO_TASK',
  EDIT_TODO_TASK :'EDIT_TODO_TASK',
  ADD_TODO_SECTION: 'ADD_TODO_SECTION',
  DELETE_TODO_SECTION:'DELETE_TODO_SECTION',
  DELETE_ONE_SECTION:" DELETE_ONE_SECTION",
  SELECTED_TASK:"SELECTED_TASK"
};
